# Generated by Django 4.1.2 on 2022-11-21 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_street_address1', models.CharField(blank=True, max_length=150, null=True)),
                ('default_street_address2', models.CharField(blank=True, max_length=150, null=True)),
                ('default_city_or_town', models.CharField(blank=True, max_length=150, null=True)),
                ('default_county', models.CharField(blank=True, max_length=100, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=15, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('default_telephone', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
