# Generated by Django 4.1.2 on 2022-10-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=250)),
                ('street_address1', models.CharField(max_length=150)),
                ('street_address2', models.CharField(blank=True, max_length=150, null=True)),
                ('city_or_town', models.CharField(max_length=150)),
                ('county', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=15)),
                ('country', models.CharField(default='Ireland', max_length=100)),
                ('telephone', models.CharField(max_length=25)),
                ('website', models.URLField(blank=True, null=True)),
                ('map_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('featured_image', models.ImageField(upload_to='')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('published', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.location')),
            ],
        ),
    ]
