# Generated by Django 4.1.2 on 2022-10-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_capacity_location_venue_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, default='media/venue_images/placeholder_anvil.jpeg', null=True, upload_to='media/event_images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='venue_image',
            field=models.ImageField(blank=True, default='media/venue_images/placeholder_anvil.jpeg', null=True, upload_to='media/venue_images'),
        ),
    ]
