# Generated by Django 4.1.2 on 2022-10-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=5.0),
            preserve_default=False,
        ),
    ]
