# Generated by Django 4.1.2 on 2022-10-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_price_alter_event_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'start_time']},
        ),
    ]
