# Generated by Django 4.1.2 on 2022-11-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, default='placeholder-images/placeholder_anvil.jpeg', null=True, upload_to='event_images'),
        ),
        migrations.AlterField(
            model_name='location',
            name='venue_image',
            field=models.ImageField(blank=True, default='placeholder-images/Warner_Bros_logo.png', null=True, upload_to='venue_images'),
        ),
    ]
