# Generated by Django 4.1.2 on 2022-11-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, default='placeholder_images/placeholder_anvil.jpeg', null=True, upload_to='event_images'),
        ),
        migrations.AlterField(
            model_name='location',
            name='venue_image',
            field=models.ImageField(blank=True, default='placeholder_images/Warner_Bros_logo.png', null=True, upload_to='venue_images'),
        ),
    ]
