# Generated by Django 4.1.2 on 2022-11-21 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0002_alter_booking_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='profiles.userprofile'),
        ),
    ]
