# Generated by Django 4.1.2 on 2022-11-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_total_alter_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='original_cart',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
